name: Powerboosts
version: 1.0-SNAPSHOT
main: io.github.hotlava03.powerboosts.Powerboosts
softdepend: [Factions, Vault]
authors: [HotLava03]
description: MassiveCraft Factions Spigot plugin for adding powerboosts through economy
commands:
  buypower:
    description: Buy power for your faction
    aliases: [bp, powerboost]
  powerboosts:
    description: Main command
permissions:
  powerboosts.admin:
    description: Bypass restrictions and economy on purchasing power for other factions
  powerboosts.use:
    description: Use the plugin generally
